# Generated by Django 4.1 on 2023-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='إضافة إسم متغير '),
        ),
    ]
