# Generated by Django 4.1 on 2023-08-24 17:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0002_brandprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='business_user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشخص المسئول'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='country_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='mobile1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='موبايل 1'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='scoial_link',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name=' لينك السوشيال ميديا الرئيسية'),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='state_c',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country_c', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.state', verbose_name='المحافظة'),
        ),
    ]
