# Generated by Django 4.1 on 2023-08-28 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0002_product_variant_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant_Dynamic_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='إضافة إسم متغير ')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.product', verbose_name='المنتج')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product_variant', verbose_name='نوع المتغير')),
            ],
        ),
    ]
