# Generated by Django 4.1 on 2023-08-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0003_product_variant_dynamic_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant_option',
        ),
        migrations.AddField(
            model_name='product',
            name='variant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v1', to='myclient.product_variant', verbose_name='نوع المتغير'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v2', to='myclient.product_variant', verbose_name='نوع المتغير'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_option1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2 إضافة إسم متغير '),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_option2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2 إضافة إسم متغير '),
        ),
        migrations.DeleteModel(
            name='Product_Variant_Dynamic_Options',
        ),
    ]
