# Generated by Django 4.1 on 2023-08-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0004_rename_product_category_bussiness_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='business_speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.bussiness_speciality', verbose_name='  تخصص البراند '),
        ),
    ]
