# Generated by Django 4.1 on 2023-09-01 00:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0005_product_cost_alter_product_variant1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='إضافة متغير جديد')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('prod_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.product_variant', verbose_name='نوع المتغير')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_option1',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='variant', chained_model_field='prod_variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr1', to='myclient.product_variant_options', verbose_name=' إسم متغير 1 '),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_option2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='variant', chained_model_field='prod_variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr2', to='myclient.product_variant_options', verbose_name=' إسم متغير 2 '),
        ),
    ]
