# Generated by Django 4.1 on 2023-09-01 00:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0006_product_variant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_option1',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='variant1', chained_model_field='prod_variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr1', to='myclient.product_variant_options', verbose_name=' إسم متغير 1 '),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_option2',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='variant2', chained_model_field='prod_variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr2', to='myclient.product_variant_options', verbose_name=' إسم متغير 2 '),
        ),
    ]
