# Generated by Django 4.1 on 2023-09-01 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0007_alter_product_variant_option1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_option1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant_option2',
        ),
    ]
