# Generated by Django 4.1 on 2023-08-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0009_alter_product_unit_name_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='إضافة متغير جديد')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('prod_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.product_variant')),
            ],
        ),
    ]
