# Generated by Django 4.1 on 2023-08-25 18:40

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0010_product_variant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product_variant', verbose_name='نوع المتغير'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_option',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='variant', chained_model_field='prod_variant', null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product_variant_options', verbose_name='إسم المتغير'),
        ),
    ]
