# Generated by Django 4.1 on 2023-09-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0010_product_variant_option1_product_variant_option2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='إضافة وحدة جديدة'),
        ),
    ]
