# Generated by Django 4.1 on 2023-09-01 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclient', '0011_alter_product_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product_variant_options',
            name='name',
            field=models.CharField(max_length=100, verbose_name='إضافة إسم متغير جديد'),
        ),
    ]
