# Generated by Django 4.1 on 2023-09-01 22:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0018_orderproduct_variant1_orderproduct_variant2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country_c',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state_c',
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.state', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product_category', verbose_name='فئة المنتج'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='الخصم '),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product', verbose_name=' إسم المنتج  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='الخصم  '),
        ),
    ]
