# Generated by Django 4.1 on 2023-09-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0019_remove_client_country_c_remove_client_state_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uid',
            field=models.CharField(max_length=500, unique=True, verbose_name='رقم الأوردر '),
        ),
    ]
