# Generated by Django 4.1 on 2023-09-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0021_alter_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=100, verbose_name='إسم شركة الشحن ')),
                ('person_name', models.CharField(max_length=100, verbose_name='إسم مسئول شركة الشحن ')),
                ('mobile1', models.CharField(max_length=11, null=True, verbose_name='موبايل المسئول')),
                ('mobile1_has_whatsapp', models.BooleanField(default=True, verbose_name=' واتس اب ؟')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='country_c',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='state_c',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.state', verbose_name='المحافظة'),
        ),
    ]
