# Generated by Django 4.1 on 2023-09-02 18:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclient', '0022_courier_remove_brandprofile_country_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BrandCourierPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='التكلفة')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.courier', verbose_name='إسم شركة الشحن ')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.state', verbose_name='المحافظة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
