# Generated by Django 4.1 on 2023-09-02 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0024_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcourierprices',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandcourierprices',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
    ]
