# Generated by Django 4.1 on 2023-09-02 22:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0025_brandcourierprices_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product', verbose_name=' إسم المنتج  '),
        ),
    ]
