# Generated by Django 4.1 on 2023-09-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0026_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product_unit', verbose_name='الوحدة'),
        ),
    ]
