# Generated by Django 4.1 on 2023-09-02 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0027_orderproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variant_option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpo1', to='myclient.product_variant_options', verbose_name=' إسم متغير 1 '),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='variant_option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpo2', to='myclient.product_variant_options', verbose_name=' إسم متغير 2 '),
        ),
    ]
