# Generated by Django 4.1 on 2023-09-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0028_alter_orderproduct_variant_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='الوحدة  '),
        ),
    ]
