# Generated by Django 4.1 on 2023-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0029_alter_orderproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(max_length=50, null=True, verbose_name='الوحدة  '),
        ),
    ]
