# Generated by Django 4.1 on 2023-09-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0030_alter_orderproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.product_unit', verbose_name='الوحدة '),
        ),
    ]
