# Generated by Django 4.1 on 2023-09-10 17:20

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0033_remove_client_user_remove_order_client_client_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcourierprices',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='courier', chained_model_field='courier', null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.state', verbose_name=' المحافظة '),
        ),
    ]
