# Generated by Django 4.1 on 2023-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0035_alter_brandcourierprices_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcourierprices',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name=' شحن مجاني؟'),
        ),
    ]
