# Generated by Django 4.1 on 2023-09-10 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0036_brandcourierprices_free_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='التكلفة')),
                ('free_shipping', models.BooleanField(default=False, verbose_name=' شحن مجاني؟')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.courier', verbose_name='إسم شركة الشحن ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.order')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.state', verbose_name='المحافظة')),
            ],
        ),
    ]
