# Generated by Django 4.1 on 2023-09-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0037_ordershippingdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='OrderClient',
        ),
    ]
