# Generated by Django 4.1 on 2023-09-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0038_rename_client_orderclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclient',
            name='is_saved',
            field=models.BooleanField(default=False, verbose_name=' مسموح بتعديل بيانات العميل؟ '),
        ),
    ]
