# Generated by Django 4.1 on 2023-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0039_orderclient_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('مسوده', 'Draft'), ('قيد التحقق', 'Pending'), ('تم التأكيد', 'Confirmed')], default='مسوده', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='is_saved',
            field=models.BooleanField(default=False, verbose_name=' غير مسموح بتعديل بيانات العميل؟ '),
        ),
    ]
