# Generated by Django 4.1 on 2023-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0040_order_order_state_alter_orderclient_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_after_shipp',
            field=models.CharField(default=0, max_length=500, null=True, verbose_name='إجمالي الطلب شامل الشحن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order_before_shipp',
            field=models.CharField(default=0, max_length=500, null=True, verbose_name='إجمالي الطلب قبل الشحن'),
        ),
    ]
